### ISSUE TITLE
Native Windows UBFC Testing gives an Error due to path splitting in DataLoader

### ISSUE THREAD

**Issue by NeilM21** [ubicomplab/rPPG-Toolbox#106]
Good afternoon,

Thank you for this toolbox first off, it was a struggle finding a deep learning rPPG repo with established dataloaders for the main public datasets.

I was running a train, test cycle on DeepPhys using the _SCAMPS_SCAMPS_UBFC_DEEPPHYS_BASIC_ yaml file and I noticed that an error was popping up when I got to the inference phase, both in _train and test_ and _test_only_ mode.  You may find the stack trace below. 

I've run the pipeline through Pycharm's debugger and I believe it's down to the __getitem__ dunder function in the BaseLoader class. It looks like on Windows, the "\\" characters implicitly inserted when the program creates directories in the preprocessing phase are causing the issue, since the `split()` function only considers the "/" character (assuming this is based on a Linux distro or similar). Can you confirm whether I've tackled it correctly? I'm quite new to PyTorch and the repo in general and want to make sure I'm working correctly. I did manage to get the MAE etc. by replacing with the single slash. 

If the approach is correct holistically, it's only a matter of inserting an extra line for the replace function for Windows users.

**Trace of original __getitem__ function on Native Windows in Pycharm**

`Traceback (most recent call last):
  File "C:\NIVS Project\GitHub Repos\rPPG-Toolbox-main\main.py", line 243, in <module>
    test(config, data_loader_dict)
  File "C:\NIVS Project\GitHub Repos\rPPG-Toolbox-main\main.py", line 85, in test
    model_trainer.test(data_loader_dict)
  File "C:\NIVS Project\GitHub Repos\rPPG-Toolbox-main\neural_methods\trainer\DeepPhysTrainer.py", line 136, in test
    sort_index = int(test_batch[3][idx])
ValueError: invalid literal for int() with base 10: '72_SizeH72_ClipLength180_DataTypeNormalized_Standardized_LabelTypeNormalized_Large_boxTrue_Large_size1'

Process finished with exit code 1
`

![__getitem__ function in BaseLoader class with slashes replaced](https://user-images.githubusercontent.com/106648077/209166055-94d17122-a7e8-4c5d-9211-a288cb7e03c3.PNG)
![original __getitem__ function in BaseLoader class](https://user-images.githubusercontent.com/106648077/209166058-dc3e9b1d-514d-4a49-aebb-84c40842a082.PNG)

**Comment by girishvn** [comment]
Hello, 
Thanks for pointing this out. You are correct. In line 118 of the baseloader file '/' should be changed to os.sep for cross os functionality. We will make this change shortly. 

Best

**Comment by NeilM21** [comment]
Thanks for your prompt reply,

No problem. Thanks again for the repo, once the change is applied you can mark this as closed.

**Comment by NeilM21** [comment]
Just noticed the PR, thanks for fixing this!

Closing this issue as discussed.
