### ISSUE TITLE
How should I deal with this problem

### ISSUE THREAD

**Issue by CosionMa** [ubicomplab/rPPG-Toolbox#263]
Traceback (most recent call last):
  File "C:/Users/user/OneDrive/desktop/codes/rPPG-s/rPPG-Toolbox-main/main.py", line 161, in <module>
    train_data_loader = train_loader(
  File "C:\Users\user\OneDrive\desktop\codes\rPPG-s\rPPG-Toolbox-main\dataset\data_loader\PURELoader.py", line 45, in __init__
    super().__init__(name, data_path, config_data)
  File "C:\Users\user\OneDrive\desktop\codes\rPPG-s\rPPG-Toolbox-main\dataset\data_loader\BaseLoader.py", line 72, in __init__
    raise ValueError(self.dataset_name,
ValueError: ('train', 'Please set DO_PREPROCESS to True. Preprocessed directory does not exist!')

**Comment by yahskapar** [comment]
Hi @CosionMa,

Can you provide more details regarding the context in which you're encountering this error? Have you already preprocessed the PURE dataset, for example, using one of the configs and while setting the `DO_PREPROCESS` command to `True`? As mentioned within the config files themselves, you will have to do this the first time you use any dataset for any unique set of related config parameters.

**Comment by CosionMa** [comment]
Thank you very much for your reply. As you said, the problem has been solved.
I am now stuck in your 'Training on SCAMPS and testing on UBFC-rPPG With DeepPhys' under 'Examples of Neural Network Training' in the 'readme' file.
 When I put 'MODEL_FILE_NAME:SCAMPS_SCAMPS_UBFC_deepphys' under 'configs/train_configs/SCAMPS_SCAMPS_UBFC-rPPG_DEEPPHYS_BASIC.yaml' in 'model_file_name: scamps_scamps_uBFC_deepphys' DATA_PATH' was updated to the path where the 'SCAMPS' dataset resides on my computer, and 'CACHED_PATH' was also updated, but my Python run yielded the following error:
Traceback (most recent call last):
  File "C:/Users/马江涛/OneDrive/桌面/codes/rPPG-s/rPPG-Toolbox-main/main.py", line 132, in <module>
    config = get_config(args)
  File "C:\Users\马江涛\OneDrive\桌面\codes\rPPG-s\rPPG-Toolbox-main\config.py", line 569, in get_config
    update_config(config, args)
  File "C:\Users\马江涛\OneDrive\桌面\codes\rPPG-s\rPPG-Toolbox-main\config.py", line 368, in update_config
    _update_config_from_file(config, args.config_file)
  File "C:\Users\马江涛\OneDrive\桌面\codes\rPPG-s\rPPG-Toolbox-main\config.py", line 347, in _update_config_from_file
    yaml_cfg = yaml.load(f, Loader=yaml.FullLoader)
  File "D:\Anaconda3\envs\rTM\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "D:\Anaconda3\envs\rTM\lib\site-packages\yaml\loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "D:\Anaconda3\envs\rTM\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\Anaconda3\envs\rTM\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "D:\Anaconda3\envs\rTM\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 362: illegal multibyte sequence
![1111](https://github.com/ubicomplab/rPPG-Toolbox/assets/162082395/351dc2f0-b5f4-42d0-af3c-951a714c02e8)
![53b1598f9f3885fb10f26812013d1d1](https://github.com/ubicomplab/rPPG-Toolbox/assets/162082395/89571928-c4c1-4b25-9ce8-22898ea217b5)

**Comment by yahskapar** [comment]
Hi @CosionMa,

Hmm, here's two things you could try:

1. Can you try a filepath without any (what I assume to be) Mandarin characters? Our toolbox hasn't really been tested with such filepaths before, so it's very possible that's the issue.
2. There's an extra `/` character in the beginning of your `DATA_PATH` for your validation set - remove that extra `/` in the beginning.

**Comment by yahskapar** [comment]
Hi @CosionMa,

I'm going to go ahead and close this issue given it seems a bit inactive. Feel free to re-open or make a new issue if you're still running into any problems.
