### ISSUE TITLE
some issues about train

### ISSUE THREAD

**Issue by wangningbin** [ubicomplab/rPPG-Toolbox#88]
Hello, I used PURE dataset to train and verify Physnet and UBFC dataset to test, and an error occurred during the training
Traceback (most recent call last):
File "/home/wnb/Public/rPPG-Toolbox-main/main.py", line 246, in <module>
train_ and_ test(config, data_loader_dict)
File "/home/wnb/Public/rPPG-Toolbox-main/main.py", line 74, in train_ and_ test
model_ trainer.train(data_loader_dict)
File "/home/wnb/Public/rPPG-Toolbox-main/neural_methods/trainer/PhysnetTrainer.py", line 68, in train
loss.backward()
File "/home/sun/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
torch.autograd. backward(self, gradient, retain_graph, create_graph, inputs=inputs)
File "/home/sun/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 150, in backward
grad_ tensors_ = _ make_ grads(tensors, grad_tensors_)
File "/home/sun/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 51, in _ make_ grads
raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs
Then I checked the definition of loss and found that you are using Neg_ Pearson defines it as follows:
class Neg_ Pearson(nn.Module):
def __ init__ (self):
super(Neg_Pearson, self).__ init__ ()
return
def forward(self, preds, labels):
cos = nn. CosineSimilarity(dim=0, eps=1e-6)
pearson = cos(preds - preds.mean(dim=0, keepdim=True), labels - labels. mean(dim=0, keepdim=True))
return 1 - pearson
Different from the definition of negative correlation coefficient mentioned in the previous article, I don't know whether it will affect the experimental results.
Would you please tell me how to solve this problem? Thank you very much

**Comment by xliucs** [comment]
Hi We are fixing the physnet with this PR: https://github.com/ubicomplab/rPPG-Toolbox/pull/93

**Comment by xliucs** [comment]
It is been fixed.
